

remote theme:      BlackrockDigital/startbootstrap-clean-blog-jekyll

title:             solbi's blog
email:             solbi823@gmail.com
description:       personal blog for studying
author:            Solbi
baseurl:           ""
url:               "http://solbi823.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
